{% set name = "mods" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charmbracelet/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d8877258877408e90889385f1d3106278e71d56223e08e35dc60b120c95c903d

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - mods --help

about:
  home: https://github.com/charmbracelet/mods
  dev_url: https://github.com/charmbracelet/mods
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: >
    A hardware-accelerated GPU terminal emulator focusing to run in desktops and browsers

extra:
  recipe-maintainers:
    - apcamargo
