{% set name = "mods" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charmbracelet/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e16268ce55b9c90395116c2c8ce4d820d18d7f0b05430d64dc69686410776231

build:
  number: 1

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - mods --help

about:
  home: https://github.com/charmbracelet/mods
  dev_url: https://github.com/charmbracelet/mods
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: AI on the command line
  description: |
    Large Language Models (LLM) based AI is useful to ingest command output and format results in Markdown, JSON, and other text based formats. Mods is a tool to add a sprinkle of AI in your command line and make your pipelines artificially intelligent.

extra:
  recipe-maintainers:
    - apcamargo
